spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    platform: POSTGRESQL
    username: postgres
    password: F4862131
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: store_shop
  rabbitmq:
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    virtual-host: DevOps
    username: DevOps
    password: DevOps
    host: localhost
server:
  port: 8082