version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres
    networks:
      - dev_ops_network
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=F4862131
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev_ops
      - PGDATA=/var/lib/postgresql/data/pgdata
  discovery:
    container_name: dev_ops
    image: dev_ops:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_ops
      host_shop_service: http://shop:8081
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - dev_ops_network
    depends_on:
      - postgresql

  shop:
    container_name: shop_service
    image: shop_service:latest
    restart: on-failure
    build:
      context: ./shop_service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_ops
      EUREKA_SERVER: http://discovery:8761/eureka/
    networks:
      - dev_ops_network
    depends_on:
      - discovery
      - postgresql
    ports:
      - "8081:8081"
    links:
      - discovery:discovery
networks:
  dev_ops_network:
    driver: bridge