spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    platform: POSTGRESQL
    username: postgres
    password: F4862131
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: devOpsProject
  rabbitmq:
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    virtual-host: DevOps
    username: DevOps
    password: DevOps
    host: localhost
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
zuul:
  routes:
    shop:
      url: ${host_shop_service:http://localhost:8081}
    store:
      url: ${host_store_shop:http://localhost:8082}
  ignored-services: '*'
ribbon:
  eureka:
    enabled: true
