spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=F4862131
    driver-class-name: org.postgresql.Driver
    data-username: postgres
    data-password: F4862131
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${SPRING_PROFILES}

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false