spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_ops
    driver-class-name: org.postgresql.Driver
    platform: POSTGRESQL
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: devOpsProject
  rabbitmq:
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    virtual-host: DevOps
    username: DevOps
    password: DevOps
    host: localhost

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
zuul:
  routes:
    shop_service:
      url: http://localhost:8081
    store_shop:
      url: http://localhost:8082
